# Generated by Django 5.0.7 on 2024-07-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('fecha', models.DateField(max_length=200)),
                ('hora', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
