# Generated by Django 5.0.7 on 2024-07-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restobar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
