# Generated by Django 4.2 on 2024-08-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restobar', '0006_galeria_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
    ]
